autoload
zyczynski/composer pull request #3
Opened 2019-01-15 11:35 UTC by zyczynski

Spójrz czy ja to dobrze robie, robiłem wg jakiegoś samouczka ale nie działało, coś pokombinowałem i zadziałało ;)
Szczerze mówiąc jeszcze tak średnio to rozumiem. Do tego jak widzisz .gitignore nie działa ;/

2019-01-15 13:22 UTC, telemetrik requested changes

2019-01-15 13:22 UTC, telemetrik commented on .idea/composer.iml
> -    <content url="file://$MODULE_DIR$" />
Czemu znowu commitujesz `.idea` ?

2019-01-15 13:22 UTC, telemetrik commented on vendor/autoload.php
> +<?php
Folder `vendor` powinien być w gitignore.

2019-01-15 13:26 UTC, zyczynski commented on .idea/composer.iml
> -    <content url="file://$MODULE_DIR$" />
no właśnie nie wiem czemu się dodaje skoro jest dodany do gitignore

2019-01-15 14:34 UTC, telemetrik commented on .idea/composer.iml
> -    <content url="file://$MODULE_DIR$" />
Bo dodałeś to we wcześniejszym komicie. Teraz:
1. usuń .idea z .gitignore i zakomituj
2. usuń .idea to z gita (git remove chyba) i zakomituj
3. dodaj .idea do .gitignore i zakomituj

2019-01-15 14:35 UTC, telemetrik commented on .idea/composer.iml
> -    <content url="file://$MODULE_DIR$" />
To samo z vendor (już to zakomitowałeś)

2019-01-16 18:21 UTC, zyczynski commented on .idea/composer.iml
> -    <content url="file://$MODULE_DIR$" />
łączyć?

2019-01-17 09:07 UTC, telemetrik commented on .idea/composer.iml
> -    <content url="file://$MODULE_DIR$" />
Nie rozumiem pytania.

2019-01-17 09:08 UTC, telemetrik commented on vendor/autoload.php
> +<?php
W tym PR nie powinno być niczego zakomitowanego z vendor

2019-01-17 09:08 UTC, telemetrik commented on .gitignore
> +.idea,
Czemu przecinek?

2019-01-17 19:03 UTC, zyczynski commented on .gitignore
> +.idea,
Nie wiem, tak intuicyjnie. Jeśli wymienia się jakieś elementy to przeważnie stawia się przecinek.

2019-01-17 19:04 UTC, zyczynski commented on .idea/composer.iml
> -    <content url="file://$MODULE_DIR$" />
Czy mergeować ;)

2019-01-18 10:28 UTC, telemetrik approved these changes

2019-01-18 10:43 UTC, merged