klasa kalkulatora
zyczynski/composer pull request #5
Opened 2019-01-22 10:47 UTC by zyczynski

2019-01-22 15:25 UTC, telemetrik requested changes

2019-01-22 15:25 UTC, telemetrik commented on app/Money/Calculator/Amount.php
> +class Amount
Jeżeli to jest kalkulator to dlaczego nazywa się "amount" ?

2019-01-22 15:25 UTC, telemetrik commented on app/Money/Calculator/Amount.php
> +        $this->value1=Money::PLN(800);
Dlaczego zapisujesz na sztywno wartości zamiast podawać ich z zewnątrz klasy? W ten sposób tym kalkulatorem mozesz obliczyc tylko sumę "80 zł + 80 zł". Równie dobrze klasa mogłaby się nazywać `Add80PLNTo80PLNCalculator`.

2019-01-22 16:37 UTC, zyczynski commented on app/Money/Calculator/Amount.php
> +class Amount
nie wiem, chyba nie chciałem żeby podprzestrzeń nazywała się tak samo jak klasa, bo jeszce mi się to wszystko miesza

2019-01-23 12:22 UTC, telemetrik commented on app/Money/Calculator/Amount.php
> +class Amount
Nazywaj rzeczy po funkcji, którą spełniają.

2019-01-23 12:23 UTC, telemetrik commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
Czemu w konstruktorze? Teraz żeby obliczyć dwie pary musisz tworzyć dwie instancje kalkulatora. Jaki jest cel żeby trzymać stan w kalkulatorze?

2019-01-23 12:25 UTC, zyczynski commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
a już myślałem :D

2019-01-23 12:26 UTC, zyczynski commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
Dwie instancje czyli dwa obiekty? Ja tu mam jeden i liczy....

2019-01-23 14:20 UTC, telemetrik commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
To zrób ćwiczenie - w pliku index dodaj dwa obliczenia - dla kwoty netto i brutto sumy 10 PLN + 49 PLN. Zobaczysz o co chodzi.

2019-01-23 14:48 UTC, zyczynski commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
No już wiem o co chodzi. oczywiście źle przeczytałem to co napisałeś i zgubiłem "pary"

2019-01-30 12:58 UTC, zyczynski commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
Nie no nie wiem, poddaje się. Wytłumacz mi o co chodzi albo coś podpowiedz bo mnie tu zaraz strzeli i krew nagła zaleje ;]

2019-01-30 20:11 UTC, telemetrik commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
Własności w klasie oznaczają, że klasa ma jakiś stan. Kalkukator służy tylko do obliczeń więc niepotrzebne mu $value1 i $value2 są niepotrzebne w klasie. Dostałeś młotek więc wszystko jest teraz dla Ciebie gwoździem. :) Dla udowodnienia, że to bez sensu zrób ćwiczenie - w pliku index dodaj dwa obliczenia - 10 PLN + 49 PLN i 20 PLN + 23 PLN. Będziesz musiał zrobić dwie instancje (new calculator) - po co? W prawdziwym życiu - kupujesz nowy kalkulator jak obliczysz jedno działanie?

2019-02-04 17:38 UTC, zyczynski commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
Tak, jak koncepcje rozumiem, ale za cholerę nie wiem jak to inaczej zapisać bezbłędnie ...;/

2019-02-04 18:23 UTC, telemetrik commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
No bez własności private $valueX w klasie.

2019-02-05 19:24 UTC, telemetrik commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
Kumasz o co chodzi teraz?

2019-02-05 19:26 UTC, zyczynski commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
chyba tak, zafiksowałem się na innym fragmencie i tak jak bym tego w ogóle nie widział ;/

2019-02-05 19:28 UTC, telemetrik commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
No to wytłumacz mi kiedy byś dodał własności w klasie a kiedy nie. :)

2019-02-05 19:30 UTC, zyczynski commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
Wtedy kiedy będzie to stała wartość, jak nazwisko, email, login etc. Jeśli zmienna to nie.

2019-02-05 20:28 UTC, telemetrik commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
Email możesz zmienić - to co z nim?

2019-02-06 09:07 UTC, zyczynski commented on app/Money/Calculator/Calculator.php
> +    function __construct($value1,$value2)
Teoretycznie nazwisko też :) Nie no, myślę że powinien być dodany. Teoretycznie zmienić można, ale na pewno nie będzie zmieniany często. To są wartości przypisane do obiektu, jeden obiekt - jeden zestaw własności.

2019-02-06 13:13 UTC, telemetrik approved these changes

2019-02-06 13:25 UTC, merged